### ISSUE TITLE
 java.lang.IllegalArgumentException: Bad direction -100

### ISSUE THREAD

**Issue by ameerhamza6733** [StephenVinouze/KontinuousSpeechRecognizer#1]
when i try to run app i got this error at this function

Tested on v5.1.1 on

```
private fun muteRecognition(mute: Boolean) {
        val  flag = if (mute) AudioManager.ADJUST_MUTE else AudioManager.ADJUST_UNMUTE
        audioManager.adjustStreamVolume(AudioManager.STREAM_MUSIC, flag, 0)
        audioManager.adjustStreamVolume(AudioManager.STREAM_SYSTEM, flag, 0)
    }
```
 ```
at android.os.Parcel.readException(Parcel.java:1550)
                                                                                                          at android.os.Parcel.readException(Parcel.java:1499)
                                                                                                          at android.media.IAudioService$Stub$Proxy.adjustStreamVolume(IAudioService.java:1026)
                                                                                                          at android.media.AudioManager.adjustStreamVolume(AudioManager.java:1141)
                                                                                                          at com.github.stephenvinouze.core.managers.KontinuousRecognitionManager.muteRecognition(KontinuousRecognitionManager.kt:69)
                                                                                                          at com.github.stephenvinouze.core.managers.KontinuousRecognitionManager.onReadyForSpeech(KontinuousRecognitionManager.kt:78)
                                                                                                          at android.speech.SpeechRecognizer$InternalListener$1.handleMessage(SpeechRecognizer.java:453)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5912)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)](url)
```

**Comment by StephenVinouze** [comment]
Hi, thanks for reporting this. I will look into it as soon as I've some time for me. Seems that there are some issues depending on SDK version. Could be please provide me your OS and device model ?

**Comment by ameerhamza6733** [comment]
` compileSdkVersion 25
buildToolsVersion "25.0.3"`

and my device OS 5.1.1

**Comment by leonardo7397** [comment]
Same problem here! 
CompileSdkVersion 26

**Comment by StephenVinouze** [comment]
Sorry guys for this very late reply...
I just release a patch version that should handle the OS issue for the mute feature.
Also took advantage to upgrade to the latest version of Kotlin and Android libraries.
Hope this helps you :)
