### ISSUE TITLE
crash when recognizing the keyword

### ISSUE THREAD

**Issue by vasquezdennisalon** [StephenVinouze/KontinuousSpeechRecognizer#8]
Good morning.
I was testing your project but when it recognizes the keyword it immediately causes the app to crash and the error code it throws at me is

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.recognitionspeech, PID: 5485
    java.lang.SecurityException: Not allowed to change Do Not Disturb state
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.media.IAudioService$Stub$Proxy.adjustStreamVolume(IAudioService.java:2892)
        at android.media.AudioManager.adjustStreamVolume(AudioManager.java:928)
        at com.github.stephenvinouze.core.managers.KontinuousRecognitionManager.muteRecognition(KontinuousRecognitionManager.kt:74)
        at com.github.stephenvinouze.core.managers.KontinuousRecognitionManager.onReadyForSpeech(KontinuousRecognitionManager.kt:91)
        at android.speech.SpeechRecognizer$InternalListener$1.handleMessage(SpeechRecognizer.java:453)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.audio.AudioService.checkForRingerModeChange(AudioService.java:4698)
        at com.android.server.audio.AudioService.adjustStreamVolume(AudioService.java:2163)
        at com.android.server.audio.AudioService.adjustStreamVolume(AudioService.java:1977)
        at android.media.IAudioService$Stub.onTransact(IAudioService.java:1258)
        at android.os.Binder.execTransactInternal(Binder.java:1021)`

**Comment by kas84** [comment]
You can check if (Settings.Global.getInt(context.contentResolver, "zen_mode" ) == 0) it will RequiresApi(Build.VERSION_CODES.JELLY_BEAN_MR1) though.

https://github.com/kas84/KontinuousSpeechRecognizer/blob/f60bf4d76d068605064e33c437a9d01addb6aec8/core/src/main/kotlin/com/github/stephenvinouze/core/managers/KontinuousRecognitionManager.kt#L74
